name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

publish_to: none
# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.6.0
  command_runner:
    path: ../command_runner
    
    

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
